export const listaCitas = [
  {
    id: 1,
    paciente: "juan",
    hora: "20:00",
    dia: "Sabado",
    fecha: "22/4",
    consulta: "Pie",
  },
  {
    id: 2,
    paciente: "nestor",
    hora: "15:00",
    dia: "Martes",
    fecha: "27/4",
    consulta: "Poco aguante",
  },
  {
    id: 3,
    paciente: "carlos",
    hora: "19:00",
    dia: "Lunes",
    fecha: "21/4",
    consulta: "Tos con sangre",
  },
  {
    id: 4,
    paciente: "bruno",
    hora: "19:00",
    dia: "Martes",
    fecha: "24/4",
    consulta: "Prostata",
  },
  {
    id: 5,
    paciente: "ruben",
    hora: "15:00",
    dia: "Miercoles",
    fecha: "24/4",
    consulta: "Malestar",
  },
  {
    id: 6,
    paciente: "ruben",
    hora: "15:00",
    dia: "Viernes",
    fecha: "26/4",
    consulta: "Dolor de cabeza",
  },
  {
    id: 7,
    paciente: "roberto",
    hora: "10:00",
    dia: "Viernes",
    fecha: "24/4",
    consulta: "Diarrea",
  }
];
